---
title: "Fed techinal check"
author: "NBO lab"
date: '2023-02-22'
output: 
    html_document:
        fig_caption: yes
        theme: cerulean
        toc: yes
        toc_depth: 3
        toc_float: yes
---

# Bateria

La revision de la bateria consiste en dejar el FED con su respectiva bateria corriendo el programa ~/fed_techical_check/scripts/testing/battery_test. Una vez cargado el programa debes dejar andando por 24 horas. El programa hace girar el disco del FED y toma muestras del nivel de bateria cada 1 segundo. Esto queda guardado en la microsd. Una vez terminadas las 24 horas debes ir a fed_techical_check/scripts/analysis y buscar el script fed_batt_analysis.R

## Testeando la capacidad de la bateria

1. Abre la tarjeta microsd en tu computador y entra al archivo config.txt y modifica el parametro randomFeed, para el testeo de bateria pon el numero '99' sin las comillas  y guarda el archivo

2. Carga el programa battery_test ocupando platformio, si estas desde la terminal ocupa el codigo 'pio run -d ~/fed_techical_check/scripts/testing/battery_test -t upload' asegurandone de tener el FED conectado y con la bateria

3. Espera 24 horas para desconectar la bateria y remover la tarjeta microsd

4. Realiza una copia del archivo [numero fed].CSV en tu escritorio

5. Abre el script fed_batt_analysis.R y sigue las instrucciones que hay dentro

### Si la bateria esta por debajo de la capacidad esperada

Marca la bateria indicando la fecha del test y el ultimo voltaje registrado.

### Battery is at or above expected capacity

Recarga la bateria para utilizarla posteriormente.


# Motor

## Testing RPM or motor turns per seconds

### Motor turns slower than expected

### Motor turns at proper speed

## Checking M1 and M2 connectivity

### Multimeter outputs no signal

### Multimeter signals correct connectivity

## Checking Feather M0 to motor shield power relay


# Infrared sensor

## Checking sensor detection area

### Sensor detection area is less than expected (or nonexistent)

### Sensor detection area is as expected

## Checking sensor digital signal

### There is no digital signal present

See [Checking signal wire](#Checkingsignalwire)

### Digital signal output is as expected

## Checking sensor resistance

### Resistance is damaged or resistance lectures are not expected

# Checking signal wire {#Checkingsignalwire}

## Signal wire is unsoldered or damaged

## Signal wire is properly connected, resolder or replaced


# 3D parts integrity

## Comparing 3D parts against original STL file

### Parts are damaged or not similar to STL file

### Parts are as expected

See [Pellet delivery stress test](#Pelletdeliverystresstest)


# Pellet delivery stress test {#Pelletdeliverystresstest}

## Unloading full silo

### Unloading presents errors

### Unloading goes as expected

FED is succesfuly tested, and present no errors.

